site :opscode

cookbook "lemp", git: "https://github.com/DanielChalk/lemp-cookbook.git"
cookbook "php54", git: "https://github.com/DanielChalk/php54-cookbook.git"
cookbook "nginx"
cookbook "mysql"
cookbook "database"
